services:
  db:
    container_name: some-postgis
    image: docker.io/postgis/postgis:17-3.5-alpine
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      # POSTGRES_DB: mydatabase
    # ports:
      # - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - some-network

  admin:
    image:  docker.io/dpage/pgadmin4:9.4.0
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - admin_data:/var/lib/pgadmin

networks:
  some-network:
    driver: bridge

volumes:
  db_data:
  admin_data:
